app_name: ninjam-dj-bot
log_file: stdout
log_level: debug
lang: en_GB
http_port: 8080
db_file: ./tracks/tracks.db
tracks_dir: ./tracks
lv2host_config: lv2host.yaml
daemon: false
server:
  host: guitar-jam.ru
  port: 2051
  anonymous: true
  user_name: dj
  user_password:
player:
  dir:
  command: mpg321
  args: -o pulse